
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://setyterzbpejjvsgesqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNldHl0ZXJ6YnBlamp2c2dlc3FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjgxNTgsImV4cCI6MjA2MjA0NDE1OH0.OTSMbhUNdwd5iC4eNNyrVP0UejYXHp28k9tJeCJg0J0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
